style->menu_frame_font, style->menu_frame_pixmap, style->menu_hilite_pixmap,
    style->menu_hilite_selected_pixmap, style->menu_hilite_submenu_pixmap,
    style->menu_hilite_unselected_pixmap, style->menu_selected_pixmap,
    style->menu_submenu_pixmap, style->menu_title_font_effect,
    style->menu_title_font, style->menu_title_pixmap,
    style->menu_unselected_pixmap, style->menuFont, style->slit_pixmap,
    style->titleFont, style->toolbar_button_pixmap,
    style->toolbar_button_pressed_pixmap, style->toolbar_clock_font,
    style->toolbar_clock_pixmap, style->toolbar_font,
    style->toolbar_iconbar_empty_pixmap,
    style->toolbar_iconbar_focused_font_effect,
    style->toolbar_iconbar_focused_font, style->toolbar_iconbar_focused_pixmap,
    style->toolbar_iconbar_unfocused_font,
    style->toolbar_iconbar_unfocused_pixmap, style->toolbar_label_pixmap,
    style->toolbar_pixmap, style->toolbar_windowLabel_pixmap,
    style->toolbar_workspace_font, style->toolbar_workspace_pixmap,
    style->window_close_pixmap, style->window_close_pressed_pixmap,
    style->window_close_unfocus_pixmap, style->window_font_effect,
    style->window_font, style->window_grip_focus_pixmap,
    style->window_grip_unfocus_pixmap, style->window_handle_focus_pixmap,
    style->window_handle_unfocus_pixmap, style->window_iconify_pixmap,
    style->window_iconify_pressed_pixmap, style->window_iconify_unfocus_pixmap,
    style->window_label_focus_font, style->window_label_focus_pixmap,
    style->window_label_pixmap, style->window_label_unfocus_pixmap,
    style->window_maximize_pixmap, style->window_maximize_pressed_pixmap,
    style->window_maximize_unfocus_pixmap, style->window_menuicon_pixmap,
    style->window_menuicon_pressed_pixmap,
    style->window_menuicon_unfocus_pixmap, style->window_shade_pixmap,
    style->window_shade_pressed_pixmap, style->window_shade_unfocus_pixmap,
    style->window_stick_pixmap, style->window_stick_pressed_pixmap,
    style->window_stick_unfocus_pixmap, style->window_stuck_pixmap,
    style->window_stuck_pressed_pixmap, style->window_stuck_unfocus_pixmap,
    style->window_tab_font, style->window_title_focus_pixmap,
    style->window_title_unfocus_pixmap, style->window_unshade_pixmap,
    style->window_unshade_pressed_pixmap, style->window_unshade_unfocus_pixmap,
